### ISSUE TITLE
Log все время заполняется ошибками

### ISSUE THREAD

**Issue by ismail0vv** [asyncdargen/evo-plus#23]
Oct 19, 2024 10:45:12 PM ru.dargen.evoplus.api.event.EventBus fire
SEVERE: Error while event dispatch class ru.dargen.evoplus.api.event.world.block.BlockEntityUpdateEvent
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at ru.dargen.evoplus.util.evo.BlocksKt.getPlayerSkullTextureValue(blocks.kt:21)
	at ru.dargen.evoplus.util.evo.Shard.isThis(blocks.kt:65)
	at ru.dargen.evoplus.util.evo.BlocksKt.getShard(blocks.kt:25)
	at ru.dargen.evoplus.features.esp.ESPFeature.recognizeBlock(ESPFeature.kt:90)
	at ru.dargen.evoplus.features.esp.ESPFeature.tryToRecognizeBlock(ESPFeature.kt:84)
	at ru.dargen.evoplus.features.esp.ESPFeature.access$tryToRecognizeBlock(ESPFeature.kt:29)
	at ru.dargen.evoplus.features.esp.ESPFeature$5.invoke(ESPFeature.kt:66)
	at ru.dargen.evoplus.features.esp.ESPFeature$5.invoke(ESPFeature.kt:66)
	at ru.dargen.evoplus.api.event.EventBus.fire(EventBus.kt:20)
	at ru.dargen.evoplus.api.event.EventBus.fireResult(EventBus.kt:26)
	at net.minecraft.class_2818.handler$zbf000$evo-plus$setBlockEntity(class_2818.java:731)
	at net.minecraft.class_2818.method_12007(class_2818.java)
	at net.minecraft.class_2818.method_12216(class_2818.java:332)
	at net.minecraft.class_2818.method_12201(class_2818.java:320)
	at net.minecraft.class_2818.method_31716(class_2818.java:460)
	at net.minecraft.class_6603.method_38593(class_6603.java:107)
	at net.minecraft.class_6603.method_38588(class_6603.java:96)
	at net.minecraft.class_2818.method_12224(class_2818.java:458)
	at net.minecraft.class_631.method_16020(class_631.java:117)
	at net.minecraft.class_634.method_38539(class_634.java:763)
	at net.minecraft.class_634.method_11128(class_634.java:735)
	at net.minecraft.class_2672.method_11528(class_2672.java:45)
	at net.minecraft.class_2672.method_11054(class_2672.java:12)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
	
	вот ошибка которая все время повторяется

**Comment by ismail0vv** [comment]
Oct 19, 2024 10:18:44 PM ru.dargen.evoplus.service.EvoPlusService fetchIngamePlayers
SEVERE: Error while fetch ingame players
ru.dargen.rest.response.ResponseException: NOT_FOUND(404)
	at ru.dargen.rest.response.Response.rethrow(Response.java:27)
	at ru.dargen.rest.proxy.executor.ResponseBodyExecutor.execute(ResponseBodyExecutor.java:19)
	at ru.dargen.rest.proxy.executor.AbstractExecutor.apply(AbstractExecutor.java:43)
	at ru.dargen.rest.proxy.executor.AbstractExecutor.apply(AbstractExecutor.java:15)
	at ru.dargen.rest.proxy.BindingInvocationHandler.invoke(BindingInvocationHandler.java:29)
	at jdk.proxy2/jdk.proxy2.$Proxy95.checkPlayers(Unknown Source)
	at ru.dargen.evoplus.service.EvoPlusService.fetchIngamePlayers(EvoPlusService.kt:55)
	at ru.dargen.evoplus.service.EvoPlusService.fetchIngamePlayers$default(EvoPlusService.kt:46)
	at ru.dargen.evoplus.service.EvoPlusService$2.invoke(EvoPlusService.kt:39)
	at ru.dargen.evoplus.service.EvoPlusService$2.invoke(EvoPlusService.kt:39)
	at ru.dargen.evoplus.api.scheduler.task.AbstractTask.execute0(AbstractTask.kt:27)
	at ru.dargen.evoplus.api.scheduler.task.AbstractTask$execute$1.invoke(AbstractTask.kt:32)
	at ru.dargen.evoplus.api.scheduler.task.AbstractTask$execute$1.invoke(AbstractTask.kt:32)
	at ru.dargen.evoplus.util.MiscKt.catch(misc.kt:12)
	at ru.dargen.evoplus.api.scheduler.task.AbstractTask.execute(AbstractTask.kt:32)
	at ru.dargen.evoplus.api.scheduler.Scheduler.tryExecute(Scheduler.kt:64)
	at ru.dargen.evoplus.api.scheduler.Scheduler.access$tryExecute(Scheduler.kt:12)
	at ru.dargen.evoplus.api.scheduler.Scheduler$runAsync$1.invoke$lambda$1$lambda$0(Scheduler.kt:42)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.FileNotFoundException: https://evo-plus.dargen.space/POST /api/ingame/check/batch
	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor104.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2057)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:2052)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:2051)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1609)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at ru.dargen.rest.client.HttpBuiltinRestClient.execute(HttpBuiltinRestClient.java:54)
	at ru.dargen.rest.client.AbstractRestClient.execute(AbstractRestClient.java:25)
	at ru.dargen.rest.proxy.executor.AbstractExecutor.executeRequest(AbstractExecutor.java:29)
	at ru.dargen.rest.proxy.executor.ResponseBodyExecutor.execute(ResponseBodyExecutor.java:18)
	... 22 more
Caused by: java.io.FileNotFoundException: https://evo-plus.dargen.space/POST /api/ingame/check/batch
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1996)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(HttpURLConnection.java:3279)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getHeaderFields(HttpsURLConnectionImpl.java:253)
	at ru.dargen.rest.client.HttpBuiltinRestClient.execute(HttpBuiltinRestClient.java:50)
	... 25 more
ну и эта тоже постоянно повторяется
